### PR TITLE
Implemented my capture function

### PR DESCRIPTION
**Pull request by cliffplaysdrums**
Modified place_piece to use captured_pieces, which in turn uses eval_piece. Added 'help' comments to new_game and place_piece.

I've only done a small amount of testing so far, but this seems to be working. I need to review the scoring of the game a little more, and then I'll make a modified version of this code to do the scoring as well, and it will work exactly as we discussed.

I'm making it a pull request and not a merge because I modified David's code. If we're sure we want to use mine (maybe wait until I do scoring to see that it's working), someone can merge it with the master branch.

### CODE REVIEW

**Comment by cliffplaysdrums** [comment]
There is a bug near the top edge. I'm working to find it.

Edit: If there are adjacent pieces of the same color, it's recursively checking those 2 pieces back and forth. I designed it not to do that, but it still is for some reason. Still looking.

**Comment by dbinnion** [comment]
I'll approve after testing is done to fix any bugs.

**Comment by dbinnion** [comment]
I don't think you have my file for game automation, so I'll add that.  This uploaded version was the most recent copy of the code I sent, right?

**Comment by cliffplaysdrums** [comment]
I thought I grabbed the most recent, but I just double checked my email, and it doesn't match. If you want to merge them, go ahead. Otherwise, I'll do it sometime today. I also added some automation to this branch in the pull request, so I'll compare them as well.

Also, the group capture appears to be working fine now in this branch (I found a stray semicolon after an if statement). I believe you can fetch this branch if you want to try any of it out. I've been looking into implementing the scoring with the group capture function, but I just don't know how to clear the board.

**Comment by rubygogri** [comment]
Not sure if I can reply via gmail to github..
I shall merge my scoring function this weekend, have my final exam this
Friday for one of my courses.. (include input from your code for the board
to score since for now the code as a static matrix to check the scoring
functionality)

@Cliff - Not sure about this - 'I've been looking into implementing the
scoring with the group capture function, but I just don't know how to clear
the board.' What exactly are you planning to implement? The function I have
written for scoring, successfully would detect the group capture but would
just have to run it for the current move as my function is working for the
matrix as a whole and traversing element by element.

**Comment by rubygogri** [comment]
I shall merge my scoring function this weekend, have my final exam this Friday for one of my courses.. (include input from your code for the board to score since for now the code has a static matrix to check the scoring functionality)

@Cliff - Not sure about this - 'I've been looking into implementing the scoring with the group capture function, but I just don't know how to clear the board.' What exactly are you planning to implement? The function I have written for scoring, successfully would detect the group capture but would just have to run it for the current move as my function is working for the matrix as a whole and traversing element by element.
[Scoring.zip](https://github.com/cliffplaysdrums/ai_go/files/539414/Scoring.zip)

**Comment by cliffplaysdrums** [comment]
@rubygogri I'll look at your code asap today. If you have a working scoring function, there's no need for me to worry about trying to do it. I just remember that David had a way to make use of the group capture once the board was cleared, but I don't know how to clear the board. If yours works, we'll use that and start focusing on the player profiles as soon as we can.

**Comment by dbinnion** [comment]
Does that scoring function go along with that link I sent that elaborated
upon the different scoring styles?  It doesn't matter which is picked since
they're both accurate methods used by the AGA.

-David Binnion
678-923-0254

**Comment by rubygogri** [comment]
Il work on the scoring function Cliff, you needn't work on it.
Lets discuss the scenario of the clearing the board tomorrow after class.
Is it you are trying to clear the board in case of a group capture?
About the scoring, I haven't got a chance to see the aga link, but I am
counting the number of coins, its area and komi, read from multiple scoring
sources online.

**Comment by cliffplaysdrums** [comment]
I believe everything is good to go now. I'll test more in Matlab when I'm home (I've been running it in Octave). I added David's automation which works fine with what I had already done. I also moved code that isn't being used to a separate directory, but it's still in this branch if we need to get it back.

If it's okay with both of you, I'll probably just merge this branch myself tomorrow. I just figure it will be easier because of the restructuring of the directory. If there are any problems with this branch or the moving I did of other files, just let me know, and I won't merge.

@rubygogri I was only trying to clear the board for scoring. Don't worry about it. When you have some of the scoring done, go ahead and put it in the master branch (if it's in a new file).

**Comment by dbinnion** [comment]
This code does not yet check for if the space is currently occupied by another piece.

**Comment by dbinnion** [comment]
There's a function in mine that does that.  Or couple of lines of code.  I don't remember which.

**Comment by dbinnion** [comment]
this line specifically:
if strcmpi(board_state(point(1),point(2)), 'n')

**Comment by dbinnion** [comment]
capture looks fine otherwise.

**Comment by dbinnion** [comment]
Delete the branch if you don't think you'll alter it any further.

**Comment by cliffplaysdrums** [comment]
Oops, I left out the part where it checks if the space is occupied to simplify testing and forgot to add it back. Good catch. Branch deleted.

**Comment by rubygogri** [comment]
Display function and some changes in new_game function

I have added the display function which is still work in progress.
A couple of bullet points:
- Currently you can choose co-ordinates from the screen which is displayed in the output as 'xcoord' and 'ycoord'.
- The co-ordinates for plotting start as (0,0) at 'bottom left corner'. (It will be clear if you check xcoord and ycoord values when you insert manually).
- I didnt want to alter your code, so the manual input 'Enter move for b (as #,#):'  now can be eliminated and the xcoord and ycoord co-ordinates can be used to add values in the board_state array.
- When the matrix size of 5 is chosen, the array length is 6X6. I am able to plot co-ordinates from boardstate(2:6,2:6). (0,0), (0,1) etc. are not getting plotted. Still working on this.
- 'Pass' button function is in progress.

**Comment by rubygogri** [comment]
I somehow thought after I committed the changes and mentioned the details of the work done, you guys might have received an email. But I guess it didnt shoot out an email.

**Comment by rubygogri** [comment]
Hi,
The code still has the following manually entering the moves and hence the display is not in sync.
        query_string = sprintf('Enter move for %s (as #,#): ', color);
        move = input(query_string, 's');

Through my code if you click on the cell (1,9), it displays a black or a white coin at 'xcoord = 1 and ycoord = 9'.
Either of you would have to change the code to "remove the functionality of manually entering the move as I have automated the move at 'mouse click' a while ago"
Please change the code so that we can test the functionality.

**Comment by cliffplaysdrums** [comment]
Hi Ruby,

I made some quick changes to force the game to rely on the GUI instead of
command window and to interact a little better (for instance the axes range
from 1-size now instead of starting from 0). Feel free to test it and
change anything.

For the remainder of the time we have, I'll be focusing on the original
command-window-only version in order to port my genetic algorithm and train
it. If it goes smoothly, I'll plug it into the GUI version so that it's
always a person playing the AI. I can't train the algorithm until the score
is done, but I'll try to finish what I can, so that if you finish that,
it'll just be a quick change.

The GUI looks nice though. Thanks for taking care of that.

**Comment by rubygogri** [comment]
Oh I was making changes and was going to commit my changes about scoring
today.
But testing is giving me a few problems since GUI input and manual input
are not in sync.

**Comment by cliffplaysdrums** [comment]
I committed my changes, so try pulling them, and see if you like it. If you
need to for the scoring, you can temporarily comment out all the GUI stuff
and just work with the command window. Which ever is easier for you.

**Pull request merged**
